apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.app.label }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.user }}
  POSTGRES_PASSWORD: {{ .Values.secret.password }}
  POSTGRES_DB: {{ .Values.secret.db }}
