apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.label }}
  labels:
    app: {{ .Values.app.label }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.container.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.app.label }}
